name: "GitHub pages: deploy main"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "22 6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Make sure to not run Jekyll
        run: touch dist/.nojekyll
      - name: Set CNAME
        run: echo "trade-and-investment-factsheets.docs.trade.gov.uk" >> dist/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          force: false
          clean-exclude: preview/
          folder: dist
          branch: gh-pages
